train_dir: dataset/train
eval_dir: dataset/eval
test_dir: dataset/test
P: p
N: n
save_path: result2

img_size: [300, 300]
epochs: 500
batch_size: 64
num_workers: 8
device: gpu

model_name: mobilnet   # resnet50 or mobilnet
DEBUG: true

# test
model_path: result/models/model_30.pth